# Wait 10ms to check files under the current directory
scan_timeout = 10

"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Make prompt single line
[line_break]
disabled = true

[character]
success_symbol = '[➜](bold #a6da95)'
error_symbol = '[✗](bold red)'

[package]
symbol = "󰏗 "

[localip]
disabled = true
ssh_only = false
format = '󰩟 [$localipv4](bold red) '

[sudo]
#style = "bold green"
#symbol = "💻 "
#disabled = false

[username]
disabled = true
#style_user = "green bold"
#style_root = "red bold"
#format = "[$user]($style) "
#show_always = true

[hostname]
disabled = true
#ssh_only = false
#format = 'on [$hostname](bold yellow) '
#trim_at = "."

[directory]
read_only = " 󰯄"
truncation_length = 4
truncate_to_repo = true
style = "bold #8aadf4"

# Substitute directory names with icons
# [directory.substitutions]
# 'Documents' = '󰈙'
# 'Downloads' = ' '
# 'Music' = ' '
# 'Pictures' = ' '

[cmd_duration]
disabled = true
#min_time = 4
#show_milliseconds = false
#style = "bold italic red"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "bold #f0c6c6"
format = "[$all_status$ahead_behind]($style)[\\)](bold #c6a0f6) "

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "
format = "  [$symbol$context]($style) "
style = "bold blue"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[c]
# symbol = " "
commands = [['gcc-15', '--version']]
format = "[gcc:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[cpp]
disabled = false
commands = [['g++-15', '--version']]
format = "[g++:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "
# detect_extensions = ["cpp", "cxx", "cc", "c++", "hpp", "hxx", "h++", "hh"]

[elixir]
# symbol = " "
format = "[elixir:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[elm]
# symbol = " "
format = "[elm:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[git_branch]
# symbol = " 󰘬 "
style = "bold #f0c6c6"
format = "[git:\\(](bold #c6a0f6)[$branch]($style)"

[golang]
# symbol = " "
format = "[golang:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[hg_branch]
symbol = "󰘬 "

[java]
# symbol = " "
format = "[java:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = " "

[nix_shell]
symbol = "󱄅 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
# symbol = " "
#pyenv_version_name = true
format = "[py:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "
format = "[ruby:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[rust]
symbol = " "
format = "[rust:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = " "

[nodejs]
format = "[node:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
