#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="CaskaydiaCove Nerd Font"
FONT2="JetBrainsMono Nerd Font"
FONT3="IBM Plex Sans"
FONT4="SF Pro Display"
FONT5="FiraCode Nerd Font"

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

bar=(
    height=33
    color=$BAR_COLOR
    shadow=off
    position=top
    sticky=on
    padding_right=20
    padding_left=20
    # blur_radius=30
    notch_width=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
    updates=when_shown
    padding_right=4
    padding_left=4
    icon.font="$FONT5:Regular:15"
    icon.color=$ICON_COLOR
    icon.padding_right=5
    icon.padding_left=5
    icon.y_offset=0
    label.font="$FONT5:Retina:13.5"
    label.color=$LABEL_COLOR
    label.padding_right=5
    label.padding_left=0
    label.y_offset=0
    background.height=25
    background.corner_radius=6
)

sketchybar --default "${defaults[@]}"

# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/aerospace.sh"

source "$ITEM_DIR/calendar.sh"

source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/dnd.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update
