return {
	{
		"nvim-treesitter/nvim-treesitter",
		branch = "master",
		lazy = false,
		build = ":TSUpdate",
		config = function()
			require("nvim-treesitter.configs").setup({
				indent = { enable = true },
				highlight = {
					enable = true,
					additional_vim_regex_highlighting = false,
				},
				ensure_installed = {
					"bash",
					"c",
					"cpp",
					"css",
					"diff",
					"html",
					"javascript",
					"jsdoc",
					"json",
					"jsonc",
					"lua",
					"luadoc",
					"luap",
					"markdown",
					"markdown_inline",
					"printf",
					"python",
					"query",
					"regex",
					"toml",
					"tsx",
					"typescript",
					"vim",
					"vimdoc",
					"xml",
					"yaml",
					"rust",
					"ron",
					"dockerfile",
					"dot",
					"go",
					"gowork",
					"gomod",
					"gosum",
					"jq",
					"scss",
					"sql",
					"zig",
					"ninja",
					"rst",
				},
				auto_install = true,
			})
		end,
	},
}
