#!/bin/bash

options=(
    style=round
    width=6
    hidpi=on
    # active_color=0xFFC4A7E7 # Pink
    # active_color=0xffcba6f7 # Purple
    active_color=0xff89b4fa # Blue
    inactive_color=0xc02c2e34
    # order=above
    # width=2
)

borders "${options[@]}"
